services:
  - type: web
    name: solomonsusuapp
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: "*"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
